

service: tr-final-project-backend


provider:
  name: aws
  runtime: nodejs12.x



functions:
  [DB name]:
    handler: handler.app
      environment:
        DB_HOST: ${opt:DB_HOST}
        DB_USER: ${opt:DB_USER}
        DB_PASSWORD: ${opt:DB_PASSWORD}
    events: 
      - http: 
          method: GET
          path: todos
          cors: true