

service: tr-final-project-backend


provider:
  name: aws
  runtime: nodejs12.x



functions:
    handler: handler.app
    events: 
      - http: 
          method: GET
          path: todos
          cors: true